### PR TITLE
[Doc] add instructions to new features

### PR DESCRIPTION
**Pull request by 2019zhou**
Signed-off-by: zhouzhou <juliazhou2019@outlook.com>

### CODE REVIEW

**Review by juntao — COMMENTED** [review]
I do not understand the "note" section. We are using hyper + http in our examples. Why mention wasmedge_http_req + https in the note?

**Comment by 2019zhou** [comment]
There are two setups for the program to work properly. One is to enable the ```wasmedge_ssl``` feature and install the httpsreq plugin, the other is to disable the  ```wasmedge_ssl``` feature.  
Because now the ```wasmedge_ssl``` feature is enabled by default in wasmedge_http_req, that means if the httpsreq plugin is not installed in Wasmedge there will be an error. The developers might need to disable the ```wasmedge_ssl``` feature or install the httpsreq plugin.

**Comment by juntao** [comment]
You can create an http client with just hyper. 

https://github.com/WasmEdge/wasmedge_hyper_demo/tree/main/client

Why do you need wasmedge_http_req here?

**Comment by 2019zhou** [comment]
OK, I will try to make this request withour using wasmedge_http_req.

**Pull request closed without merging**
