### PR TITLE
Update server to hyper

### PR DESCRIPTION
**Pull request by juntao**
Signed-off-by: Michael Yuan <michael@michaelyuan.com>

### CODE REVIEW

**Comment by juntao** [comment]
Changed the WasmEdge HTTP server to use the async hyper framework. @chenyukang Please review and test if it works correctly. Thanks.

**Comment by chenyukang** [comment]
> Changed the WasmEdge HTTP server to use the async hyper framework. @chenyukang Please review and test if it works correctly. Thanks.

Tested it, seems function works well.
But I found it's very slow, for example I tried with a very small picture, the time log is:

```console
event-481 2022-09-03 12:52:03,image-api-rust-wasi-socket,old_size: 4.61 (kb), cur_size: 18.38 (kb) cost_time: 23.184 (s)
event-480 2022-09-03 12:51:31,image-api-rust-wasi-socket,old_size: 4.61 (kb), cur_size: 18.38 (kb) cost_time: 23.423 (s)
```

Can we use WasmEdge AOT for it like this? 
https://github.com/second-state/dapr-wasm/commit/be96186e7919b97a039c27bab042e976182204ca

**Comment by chenyukang** [comment]
Updated http://23.100.38.125:9000/static/home.html to this branch for testing.

**Comment by juntao** [comment]
Hmm, it is slow. We did not use AOT and it was fast before?

**Comment by chenyukang** [comment]
No, the previous version of image-api-wasi-socket-rs is also slow.

**Comment by chenyukang** [comment]
ooo, I just have a try,
wasmedgec also works for this wasm file

```console
wasmedgec ./target/wasm32-wasi/debug/image-api-wasi-socket-rs.wasm ./target/wasm32-wasi/debug/image-api-wasi-socket-rs-opt.wasm
```
I replaced with the new wasm file, the speed now is OK.

**Review by chenyukang — APPROVED** [review]

**Pull request merged**
